User.create(username: "bob", name: "bob", password: '123')
Pet.create(name: "a cat", owner_id: User.all.last.id)
User.create(username: "dude", name: "dude", password: '123')
Pet.create(name: "cattt", owner_id: User.all.last.id)
User.create(username: "person", name: "person", password: '123')
Pet.create(name: "mor catt", owner_id: User.all.last.id)

Pet.all.last.people_friends << User.find(2)
Pet.all.second.people_friends << User.find(1)
Pet.all.first.people_friends << User.find(2)